server:
  port: 8081
  servlet:
    context-path: /display
logging:
  level:
    root: debug
feign:
  circuitbreaker:
    enabled: true # Fegin에서
  client:
    config:
      default:
        logger-level: basic


resilience4j:
  circuitbreaker:
    instances:
      cb-product-feign:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 70
        slow-call-rate-threshold: 70
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 2s
  timelimiter:
    configs:
      default:
        timeoutDuration: 7s

